# Generated by Django 5.1.5 on 2025-05-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autores", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={
                "ordering": ["nome"],
                "verbose_name": "Autor",
                "verbose_name_plural": "Autores",
            },
        ),
        migrations.AddField(
            model_name="autor",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="autor",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="autores/"),
        ),
        migrations.AddField(
            model_name="autor",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
