# Generated by Django 5.1.5 on 2025-05-15 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autores", "0002_alter_autor_options_autor_email_autor_foto_and_more"),
        ("editoras", "0001_initial"),
        ("livros", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="livro",
            options={"ordering": ["-data_publicacao"]},
        ),
        migrations.RemoveField(
            model_name="livro",
            name="autor",
        ),
        migrations.AddField(
            model_name="livro",
            name="autores",
            field=models.ManyToManyField(related_name="livros", to="autores.autor"),
        ),
        migrations.AddField(
            model_name="livro",
            name="capa",
            field=models.ImageField(blank=True, null=True, upload_to="capas/"),
        ),
        migrations.AddField(
            model_name="livro",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="livro",
            name="editora",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="livros",
                to="editoras.editora",
            ),
        ),
        migrations.AddField(
            model_name="livro",
            name="preco",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
