# Generated by Django 5.1.5 on 2025-05-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "livros",
            "0002_alter_livro_options_remove_livro_autor_livro_autores_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="data_atualizacao",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
